### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by rebecaaaaa**

### CODE REVIEW

**Comment by rebecaaaaa** [comment]
I have reviewed my StudentController & StudentDTO with Postman and the requests work with the database, but my JUnit tests keep returning errors.

**Comment by rebecaaaaa** [comment]
I have reviewed my JUnit tests and none return errors. StudentController methods successfully add a student, put a hold, and release a hold for a student.

**Comment by nyrausi** [comment]
Code is very easy to read and understand. All in all, good styling.
Code comments do help to clarify what is going on. 
All if statements check what they need to therefore logic is good.
The necessary objects are being returned and/or changed therefore correctness is good.
I've cloned the repository and have tested all the JUnit test cases myself. All passed.
The only nit is to remove commented pieces of unused code.

**Comment by rebecaaaaa** [comment]
The code has been edited to remove commented pieces of unused code. All suggestions have been resolved.

**Pull request merged**
